### PR TITLE
Feature/502 fix config validation

### LINKED ISSUE #502: Configuration properties doesn't validate if spark.emr properties are missing
**Description**
The app doesn't start when `spark.emr.clusterId` is not defined in the application properties and fails with

```
	Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobTemplateServiceImpl' defined in file [/usr/local/Cellar/tomcat/9.0.24/libexec/webapps/hyperdrive_trigger/WEB-INF/classes/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobTemplateResolutionServiceImpl' defined in file [/usr/local/Cellar/tomcat/9.0.24/libexec/webapps/hyperdrive_trigger/WEB-INF/classes/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateResolutionServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'za.co.absa.hyperdrive.trigger.configuration.application.SparkConfig': Could not bind properties to 'SparkConfig' : prefix=, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spark.emr.cluster-id' to java.lang.String
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
		at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
		at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
		... 122 more
	Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobTemplateResolutionServiceImpl' defined in file [/usr/local/Cellar/tomcat/9.0.24/libexec/webapps/hyperdrive_trigger/WEB-INF/classes/za/co/absa/hyperdrive/trigger/api/rest/services/JobTemplateResolutionServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'za.co.absa.hyperdrive.trigger.configuration.application.SparkConfig': Could not bind properties to 'SparkConfig' : prefix=, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spark.emr.cluster-id' to java.lang.String
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
		at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
		at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
		... 136 more
	Caused by: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'za.co.absa.hyperdrive.trigger.configuration.application.SparkConfig': Could not bind properties to 'SparkConfig' : prefix=, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spark.emr.cluster-id' to java.lang.String
		at org.springframework.boot.context.properties.ConfigurationPropertiesValueObjectBeanDefinition.createBean(ConfigurationPropertiesValueObjectBeanDefinition.java:52)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1231)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1173)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
		at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
		... 150 more
	Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spark.emr.cluster-id' to java.lang.String
		at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344)
		at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:469)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder$ConstructorParameter.bind(ValueObjectBinder.java:299)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:73)
		at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:473)
		at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:587)
		at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:573)
		at org.springframework.boot.context.properties.bind.Binder$Context.access$300(Binder.java:534)
		at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:471)
		at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:411)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:340)
		at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:469)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder$ConstructorParameter.bind(ValueObjectBinder.java:299)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:73)
		at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:473)
		at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:587)
		at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:573)
		at org.springframework.boot.context.properties.bind.Binder$Context.access$300(Binder.java:534)
		at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:471)
		at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:411)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:340)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329)
		at org.springframework.boot.context.properties.bind.Binder.bindOrCreate(Binder.java:321)
		at org.springframework.boot.context.properties.bind.Binder.bindOrCreate(Binder.java:306)
		at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bindOrCreate(ConfigurationPropertiesBinder.java:103)
		at org.springframework.boot.context.properties.ConfigurationPropertiesValueObjectBeanDefinition.createBean(ConfigurationPropertiesValueObjectBeanDefinition.java:49)
		... 163 more
	Caused by: za.co.absa.hyperdrive.trigger.configuration.application.NotNullValidationException: Property spark.emr.cluster-id was not defined, but is required
[2021-08-26 03:11:03,470] Artifact hyperdrive-trigger:war: Error during artifact deployment. See server log for details.
		at za.co.absa.hyperdrive.trigger.configuration.application.NotNullValidationBindHandler.onFinish(NotNullValidationBindHandlerAdvisor.scala:40)
		at org.springframework.boot.context.properties.bind.Binder.handleBindResult(Binder.java:360)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:341)
		... 188 more
```

However, the same error is not thrown in the `ApplicationStartPostgresTest`, where `SparkConfig.emr` is just `null`. Ideally, `SparkConfig.emr` should be `null` when none of the arguments for `SparkEmrSinkConfig` have been defined. Similarly, `SparkConfig.yarn` should be `null` if none of the args for `SparkYarnSinkConfig` have been defined.

The validation annotations for `SparkEmrSinkConfig` should only be validated if `SparkConfig.emr` is not null. Same for `SparkYarnSinkConfig`

**Analysis**
The `ApplicationStartPostgresTest` sets `SparkConfig.emr` to `null` because of a different behaviour in https://github.com/spring-projects/spring-boot/blob/v2.5.2/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L391 `containsNoDescendantsOf` returns `true` in the test, but returns `false` when starting the application, because the test does not contain the same properties sources. This means that the behaviour whether `SparkConfig.emr` is set to `null` or not, depends on properties sources, which is ultimately a user-input

**Solution**
Instead of relying on `SparkConfig.emr` being `null`, implement custom validation logic for the nested classes

### PR DESCRIPTION
**Pull request by kevinwallimann**
Closes #502

### CODE REVIEW

**Comment by DKTRZHR000** [comment]
This seems to be an issue with the compiler when trying to combine both .scala and .java resources, I was able to find more info here https://stackoverflow.com/questions/33836905/maven-mixing-java-and-scala-in-one-project 

I've tried the proposed solution and it seems to work fine, but it would be great if someone else could double-check it, as I'm not very familiar with maven. I've pushed it into #505

**Review by jozefbakus — DISMISSED** [review]
Tested and works

**Comment by DKTRZHR000** [comment]
Sonar seems to be unhappy about some code smells(IDK why it's green though^^), do we want to address that?

**Comment by kevinwallimann** [comment]
> Sonar seems to be unhappy about some code smells(IDK why it's green though^^), do we want to address that?

Admittedly I hoped no one would bring it up, but ok let's not be lazy. So I'll fix the duplicate string issues, but the "too many parameters" I won't fix, because this method isn't doing too many things imo. I guess it's green because there's some tolerance

**Review by jozefbakus — APPROVED** [review]

**Review by DKTRZHR000 — APPROVED** [review]

**Pull request merged**
